Merge Taxi Branch into Main (#74)
* Add YOLOv5 files (without weights file)

* Add QR code reading (not integrated with class yet)

* Refactored import paths for YOLOv5 predict

* Able to call YOLOv5 detect through Taxi.py

* Added Taxi class and functions predict_boxes and read_qr. Still need to implement details

* moved taxi to under targetAquisition

* prints coordinates

* deleted code for tflite

* updated import and added weights

* added weights

* 5 box detection update

1. removed all parameters needed when calling and hard coded in it
2. records all the box coordinates in the frame and return the function when the box number hits 5

* Update detect.py

delete white space

* updated import

* Launch detect through taxi.py; added back import statements

* Removed DS_Store

* Added README and able to launch QR detect from main

* Commented out parts of detect.py. Only need coordinates, don't need to save or view img

* Update detect.py

* Update detect.py

* Revert "Update detect.py"

This reverts commit dd4bbd51cf5c61fc57049cdc387e11585503e8ae.

* Revert "Update detect.py"

This reverts commit 633a04982b70c443807d3866df2e8bba88356dc4.

* Revert "Revert "Update detect.py""

This reverts commit 3b79f5045ad3276a0d72d0bbf0c3f59ae1dbd528.

* Revert "Revert "Update detect.py""

This reverts commit fe7f5f788d577b7be7d403bacb81d36f4519496d.

* Updated make detect into a class

* Drawing out bounding boxes

* Revert "Drawing out bounding boxes"

This reverts commit 6a1d2fdad74b71f0a4437ccf7bcb9d8287e6650f.

* Revert "Revert "Drawing out bounding boxes""

This reverts commit 4687e4c1e24d5caf35e6d0f395e1b9a50e232cd9.

* Fixed camera not launching bug

tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.

* simplified import

* unfinished

* Added comments

* updated the transaction between BOX and TRACK

also sorted the bounding box

* fixed drawing tracking box incorrectly

Ray why did you break this in your last commit lol

* detected whether QR matches or not; able to pass in object parameters at init

* pass in (x, y), (w, h) instead of (x1, y1), (x2, y2)

* add logic for stable frames

* able to switch back and forth between box, tracking, and qr (during manual testing)

* every 10 frames, print the next movement command

* Added calculate_distance()

* after moving halfway from old location to midpoint, run YOLO again to recalibrate the bbox and do recalculate distance

Note: code is untested!!! And someone needs to implement find_overlapped_bbox

* Added values for distance calculation

* Fixed some bugs, more to go

* Made constants CONSTANT_CASE

* Add YOLOv5 files (without weights file)

* Add QR code reading (not integrated with class yet)

* Refactored import paths for YOLOv5 predict

* Able to call YOLOv5 detect through Taxi.py

* Added Taxi class and functions predict_boxes and read_qr. Still need to implement details

* moved taxi to under targetAquisition

* prints coordinates

* deleted code for tflite

* updated import and added weights

* added weights

* 5 box detection update

1. removed all parameters needed when calling and hard coded in it
2. records all the box coordinates in the frame and return the function when the box number hits 5

* Update detect.py

delete white space

* updated import

* Launch detect through taxi.py; added back import statements

* Removed DS_Store

* Added README and able to launch QR detect from main

* Commented out parts of detect.py. Only need coordinates, don't need to save or view img

* Update detect.py

* Update detect.py

* Revert "Update detect.py"

This reverts commit dd4bbd51cf5c61fc57049cdc387e11585503e8ae.

* Revert "Update detect.py"

This reverts commit 633a04982b70c443807d3866df2e8bba88356dc4.

* Revert "Revert "Update detect.py""

This reverts commit 3b79f5045ad3276a0d72d0bbf0c3f59ae1dbd528.

* Revert "Revert "Update detect.py""

This reverts commit fe7f5f788d577b7be7d403bacb81d36f4519496d.

* Updated make detect into a class

* Drawing out bounding boxes

* Revert "Drawing out bounding boxes"

This reverts commit 6a1d2fdad74b71f0a4437ccf7bcb9d8287e6650f.

* Revert "Revert "Drawing out bounding boxes""

This reverts commit 4687e4c1e24d5caf35e6d0f395e1b9a50e232cd9.

* Fixed camera not launching bug

tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.

* simplified import

* unfinished

* Added comments

* updated the transaction between BOX and TRACK

also sorted the bounding box

* fixed drawing tracking box incorrectly

Ray why did you break this in your last commit lol

* detected whether QR matches or not; able to pass in object parameters at init

* pass in (x, y), (w, h) instead of (x1, y1), (x2, y2)

* add logic for stable frames

* able to switch back and forth between box, tracking, and qr (during manual testing)

* every 10 frames, print the next movement command

* Added calculate_distance()

* after moving halfway from old location to midpoint, run YOLO again to recalibrate the bbox and do recalculate distance

Note: code is untested!!! And someone needs to implement find_overlapped_bbox

* Fixed some bugs, more to go

* Fixed bugs and added total wait timer

* Put CONSTANTS at the top of the file

* taxi worker

* gitignore fix

* worker & taxi fix

* taxi remove qr

* Removed while loop and stores loop variables as object parameters

Note: not tested!!!
Still need to return pipeline object instead of printing stuff

* Added stop command to Taxi worker function

* Added stop command to Taxi Worker

* Update TaxiWorker.py

* Added Stop Commands

* Updated TaxiWorker with frame validation and stop command output

* Merged in and corrected taxi

* fixed taxi worker, requirements, and imports

Co-authored-by: f73chen <grace.fenglin@gmail.com>
Co-authored-by: rayjinghaolei <rayjinghaolei@gmail.com>
Co-authored-by: thrvg <thrvg1@gmail.com>
Co-authored-by: Fenglin Chen <55363139+f73chen@users.noreply.github.com>
Co-authored-by: Atharva Gangal <70596721+thrvg@users.noreply.github.com>
Co-authored-by: Aryan Kalia <kalia.aryan2013@gmail.com>
Co-authored-by: Michael Aizenshtadt <michael.aizenshtadt@gmail.com>
Co-authored-by: Michael Aizenshtadt <40774420+MichaelAiz@users.noreply.github.com>